//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcement()
        {
            this.UserMessage = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Context { get; set; }
        public System.DateTime NewsTime { get; set; }
        public short IsRevoke { get; set; }
        public Nullable<System.DateTime> RevokeTime { get; set; }
        public int AnnounTypeId { get; set; }
        public string Remark { get; set; }
    
        public virtual AnnounType AnnounType { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UserMessage { get; set; }
    }
}
