//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime SubTime { get; set; }
        public int ApplicantId { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> State { get; set; }
        public string Files { get; set; }
    
        public virtual ApplyType ApplyType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
