//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notepaper
    {
        public int Id { get; set; }
        public string Context { get; set; }
        public short IsComplete { get; set; }
        public int UserId { get; set; }
        public System.DateTime SubTime { get; set; }
    }
}
